version: "2"

services:
  beat:
    image: celery-exporter:latest
    build:
      context: .
    user: "65534" # TODO: see if this is needed
    volumes:
      - ./:/app
    environment:
      - BROKER_URL=redis://@redis:6379/0
    entrypoint: celery -A app beat

  worker:
    image: celery-exporter:latest
    build:
      context: .
    user: "65534" # TODO: see if this is needed
    volumes:
      - ./:/app
    environment:
      - BROKER_URL=redis://@redis:6379/0
    entrypoint: celery -A app worker -Q queue1,queue2,queue3

  exporter:
    image: celery-exporter:latest
    build:
      context: .
    volumes:
      - ./:/app
    environment:
      - BROKER_URL=redis://@redis:6379/0
      - QUEUE_LIST=queue1,queue2,queue3
      - PRIORITY_LEVELS=true
      - VERBOSE=true
    ports:
      - 8888:8888

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
